jwt:
  secret: 1234567890abcdef1234567890abcdef
  access-expiration: 3600000
  refresh-expiration: 2592000000
  remember-me-expiration: 86400000
spring:
  application:
    name: back-end
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
  mail:
    host: smtp.gmail.com
    port: 587
    username: anhn58022@gmail.com
    password: uvru mnsc rpgc ewyb
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

  # Kết nối MySQL
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  # Cấu hình Hibernate/JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

cloudinary:
  cloud-name: dxcl0xspi
  api-key: 211214697518363
  api-secret: Fv5oyDxkwVIljQ5EdfDnvf7lZ-4
logging:
  level:
    org.springframework.security: DEBUG

